name: flutter_photo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  file_picker_desktop: ^1.1.1
  path: ^1.8.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true